---
configs:
  use: 'home'
  dev:
    public_ip: '192.168.2.117'

  thedr:
    private_ip: 10.55.55.4
    virtualbox:
      cpus: 4
      memory: 4096
    vagrant:
      box: galaxy3/kamino
      box_from_file: file:///Users/korbenkirscht/repositories/github/galaxy3/kamino/package.box
    description: |
      Naboo (ucibox)
      =====================================================
      This virtual machine was created by Trilogy 2U
      for their University Cybersecurity Bootcamps.
                                                          =
      This VM was included in the G3 lab for convenience.
                              =
      =========
      Accounts:
          Vagrant: vagrant / splunk
          Admin:   admin / cybersecurity
                             =
      =======
      Splunk:
          Start:    g3enable nakadia
          Connect:  http://splunk.galaxy3.net:8000
          User:     admin / cybersecurity
                             =
