---
# tasks file for ansible

# roles/example/tasks/debian.yml
#- name: Install Packages
#  ansible.builtin.apt:
#    name: "{{item}}"
#    state: present
#  loop: "{{ pkgs }}"
#  become: yes

#
#- name: Create theDr
#  user:
#    name: thedr
#    uid: 2001
#    shell: /bin/bash
#    comment: "Master of the Universe"
#    home: /thedr
#  become: yes

- name: Install Packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs }}"
  become: yes

- name: Install Deb Packages
  apt:
    deb: "{{ item }}"
    state: present
  loop: "{{ deb_pkgs }}"
  become: yes


- name: Create xrdp group
  group:
    name: xrdp
  become: yes

- name: Add XRDP to ssl-cert group
  user:
    name: xrdp
    groups: ssl-cert
  become: yes

- name: Restart XRDP
  become: yes
  service:
    name: xrdp
    state: started

- name: Download Zenmap
  become: yes
  get_url:
    url: "https://nmap.org/dist/zenmap-7.91-1.noarch.rpm"
    dest: "/root/zenmap-7.91-1.noarch.rpm"
    mode: 0600

- name: Convert RPM to Deb
  become: yes
  command: alien /root/zenmap-7.91-1.noarch.rpm
  args:
    chdir: "/root"

- name: Install Zenmap
  become: yes
  apt:
    deb: "/root/zenmap-7.91-1.noarch.deb"
    state: present

